//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingPackFrontRevised.DataRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animal", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Animal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AnimalIDField;
        
        private int Intake_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BreedField;
        
        private System.Nullable<bool> SexField;
        
        private System.Nullable<int> ApproxAge_YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        private System.Nullable<bool> SterilisedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AnimalID {
            get {
                return this.AnimalIDField;
            }
            set {
                if ((this.AnimalIDField.Equals(value) != true)) {
                    this.AnimalIDField = value;
                    this.RaisePropertyChanged("AnimalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Intake_Number {
            get {
                return this.Intake_NumberField;
            }
            set {
                if ((this.Intake_NumberField.Equals(value) != true)) {
                    this.Intake_NumberField = value;
                    this.RaisePropertyChanged("Intake_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Breed {
            get {
                return this.BreedField;
            }
            set {
                if ((object.ReferenceEquals(this.BreedField, value) != true)) {
                    this.BreedField = value;
                    this.RaisePropertyChanged("Breed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<bool> Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ApproxAge_Year {
            get {
                return this.ApproxAge_YearField;
            }
            set {
                if ((this.ApproxAge_YearField.Equals(value) != true)) {
                    this.ApproxAge_YearField = value;
                    this.RaisePropertyChanged("ApproxAge_Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> Sterilised {
            get {
                return this.SterilisedField;
            }
            set {
                if ((this.SterilisedField.Equals(value) != true)) {
                    this.SterilisedField = value;
                    this.RaisePropertyChanged("Sterilised");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campaign", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Campaign : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime DateFromField;
        
        private System.DateTime DateToField;
        
        private bool OnlineEventField;
        
        private bool FundraiserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        private CodingPackFrontRevised.DataRef.TimeSpan TimeToField;
        
        private CodingPackFrontRevised.DataRef.TimeSpan TimeFromField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool OnlineEvent {
            get {
                return this.OnlineEventField;
            }
            set {
                if ((this.OnlineEventField.Equals(value) != true)) {
                    this.OnlineEventField = value;
                    this.RaisePropertyChanged("OnlineEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Fundraiser {
            get {
                return this.FundraiserField;
            }
            set {
                if ((this.FundraiserField.Equals(value) != true)) {
                    this.FundraiserField = value;
                    this.RaisePropertyChanged("Fundraiser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public CodingPackFrontRevised.DataRef.TimeSpan TimeTo {
            get {
                return this.TimeToField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeToField, value) != true)) {
                    this.TimeToField = value;
                    this.RaisePropertyChanged("TimeTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public CodingPackFrontRevised.DataRef.TimeSpan TimeFrom {
            get {
                return this.TimeFromField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeFromField, value) != true)) {
                    this.TimeFromField = value;
                    this.RaisePropertyChanged("TimeFrom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        private long ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private bool VolunteerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((this.ContactField.Equals(value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Volunteer {
            get {
                return this.VolunteerField;
            }
            set {
                if ((this.VolunteerField.Equals(value) != true)) {
                    this.VolunteerField = value;
                    this.RaisePropertyChanged("Volunteer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataRef.AccessServiceAPISoap")]
    public interface AccessServiceAPISoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAnimal", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.AddAnimalResponse AddAnimal(CodingPackFrontRevised.DataRef.AddAnimalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAnimal", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddAnimalResponse> AddAnimalAsync(CodingPackFrontRevised.DataRef.AddAnimalRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCampaign", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.AddCampaignResponse AddCampaign(CodingPackFrontRevised.DataRef.AddCampaignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCampaign", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddCampaignResponse> AddCampaignAsync(CodingPackFrontRevised.DataRef.AddCampaignRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.AddEmployeeResponse AddEmployee(CodingPackFrontRevised.DataRef.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddEmployeeResponse> AddEmployeeAsync(CodingPackFrontRevised.DataRef.AddEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name getAllAnimalsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllAnimals", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.getAllAnimalsResponse getAllAnimals(CodingPackFrontRevised.DataRef.getAllAnimalsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllAnimals", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllAnimalsResponse> getAllAnimalsAsync(CodingPackFrontRevised.DataRef.getAllAnimalsRequest request);
        
        // CODEGEN: Generating message contract since element name getAllCampaignsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCampaigns", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.getAllCampaignsResponse getAllCampaigns(CodingPackFrontRevised.DataRef.getAllCampaignsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCampaigns", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllCampaignsResponse> getAllCampaignsAsync(CodingPackFrontRevised.DataRef.getAllCampaignsRequest request);
        
        // CODEGEN: Generating message contract since element name getAllEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllEmployees", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.getAllEmployeesResponse getAllEmployees(CodingPackFrontRevised.DataRef.getAllEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllEmployeesResponse> getAllEmployeesAsync(CodingPackFrontRevised.DataRef.getAllEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CodingPackFrontRevised.DataRef.HelloWorldResponse HelloWorld(CodingPackFrontRevised.DataRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.HelloWorldResponse> HelloWorldAsync(CodingPackFrontRevised.DataRef.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAnimalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAnimal", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.AddAnimalRequestBody Body;
        
        public AddAnimalRequest() {
        }
        
        public AddAnimalRequest(CodingPackFrontRevised.DataRef.AddAnimalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAnimalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intakenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string breed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool sex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int approxage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool sterilised;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string size;
        
        public AddAnimalRequestBody() {
        }
        
        public AddAnimalRequestBody(int intakenumber, string name, string breed, bool sex, int approxage, int age, bool sterilised, string description, string size) {
            this.intakenumber = intakenumber;
            this.name = name;
            this.breed = breed;
            this.sex = sex;
            this.approxage = approxage;
            this.age = age;
            this.sterilised = sterilised;
            this.description = description;
            this.size = size;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAnimalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAnimalResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.AddAnimalResponseBody Body;
        
        public AddAnimalResponse() {
        }
        
        public AddAnimalResponse(CodingPackFrontRevised.DataRef.AddAnimalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAnimalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddAnimalResult;
        
        public AddAnimalResponseBody() {
        }
        
        public AddAnimalResponseBody(bool AddAnimalResult) {
            this.AddAnimalResult = AddAnimalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCampaignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCampaign", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.AddCampaignRequestBody Body;
        
        public AddCampaignRequest() {
        }
        
        public AddCampaignRequest(CodingPackFrontRevised.DataRef.AddCampaignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCampaignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime datefrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool online;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool fundraiser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime timeto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime timefrom;
        
        public AddCampaignRequestBody() {
        }
        
        public AddCampaignRequestBody(string name, string description, System.DateTime datefrom, System.DateTime dateto, bool online, bool fundraiser, string location, System.DateTime timeto, System.DateTime timefrom) {
            this.name = name;
            this.description = description;
            this.datefrom = datefrom;
            this.dateto = dateto;
            this.online = online;
            this.fundraiser = fundraiser;
            this.location = location;
            this.timeto = timeto;
            this.timefrom = timefrom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCampaignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCampaignResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.AddCampaignResponseBody Body;
        
        public AddCampaignResponse() {
        }
        
        public AddCampaignResponse(CodingPackFrontRevised.DataRef.AddCampaignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCampaignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCampaignResult;
        
        public AddCampaignResponseBody() {
        }
        
        public AddCampaignResponseBody(bool AddCampaignResult) {
            this.AddCampaignResult = AddCampaignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployee", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.AddEmployeeRequestBody Body;
        
        public AddEmployeeRequest() {
        }
        
        public AddEmployeeRequest(CodingPackFrontRevised.DataRef.AddEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contactnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool volunteer;
        
        public AddEmployeeRequestBody() {
        }
        
        public AddEmployeeRequestBody(string name, string surname, string contactnumber, string email, bool volunteer) {
            this.name = name;
            this.surname = surname;
            this.contactnumber = contactnumber;
            this.email = email;
            this.volunteer = volunteer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.AddEmployeeResponseBody Body;
        
        public AddEmployeeResponse() {
        }
        
        public AddEmployeeResponse(CodingPackFrontRevised.DataRef.AddEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddEmployeeResult;
        
        public AddEmployeeResponseBody() {
        }
        
        public AddEmployeeResponseBody(bool AddEmployeeResult) {
            this.AddEmployeeResult = AddEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllAnimalsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllAnimals", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.getAllAnimalsRequestBody Body;
        
        public getAllAnimalsRequest() {
        }
        
        public getAllAnimalsRequest(CodingPackFrontRevised.DataRef.getAllAnimalsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllAnimalsRequestBody {
        
        public getAllAnimalsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllAnimalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllAnimalsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.getAllAnimalsResponseBody Body;
        
        public getAllAnimalsResponse() {
        }
        
        public getAllAnimalsResponse(CodingPackFrontRevised.DataRef.getAllAnimalsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllAnimalsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CodingPackFrontRevised.DataRef.Animal[] getAllAnimalsResult;
        
        public getAllAnimalsResponseBody() {
        }
        
        public getAllAnimalsResponseBody(CodingPackFrontRevised.DataRef.Animal[] getAllAnimalsResult) {
            this.getAllAnimalsResult = getAllAnimalsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCampaignsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCampaigns", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.getAllCampaignsRequestBody Body;
        
        public getAllCampaignsRequest() {
        }
        
        public getAllCampaignsRequest(CodingPackFrontRevised.DataRef.getAllCampaignsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllCampaignsRequestBody {
        
        public getAllCampaignsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCampaignsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCampaignsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.getAllCampaignsResponseBody Body;
        
        public getAllCampaignsResponse() {
        }
        
        public getAllCampaignsResponse(CodingPackFrontRevised.DataRef.getAllCampaignsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCampaignsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CodingPackFrontRevised.DataRef.Campaign[] getAllCampaignsResult;
        
        public getAllCampaignsResponseBody() {
        }
        
        public getAllCampaignsResponseBody(CodingPackFrontRevised.DataRef.Campaign[] getAllCampaignsResult) {
            this.getAllCampaignsResult = getAllCampaignsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.getAllEmployeesRequestBody Body;
        
        public getAllEmployeesRequest() {
        }
        
        public getAllEmployeesRequest(CodingPackFrontRevised.DataRef.getAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllEmployeesRequestBody {
        
        public getAllEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.getAllEmployeesResponseBody Body;
        
        public getAllEmployeesResponse() {
        }
        
        public getAllEmployeesResponse(CodingPackFrontRevised.DataRef.getAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CodingPackFrontRevised.DataRef.Employee[] getAllEmployeesResult;
        
        public getAllEmployeesResponseBody() {
        }
        
        public getAllEmployeesResponseBody(CodingPackFrontRevised.DataRef.Employee[] getAllEmployeesResult) {
            this.getAllEmployeesResult = getAllEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CodingPackFrontRevised.DataRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodingPackFrontRevised.DataRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CodingPackFrontRevised.DataRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccessServiceAPISoapChannel : CodingPackFrontRevised.DataRef.AccessServiceAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessServiceAPISoapClient : System.ServiceModel.ClientBase<CodingPackFrontRevised.DataRef.AccessServiceAPISoap>, CodingPackFrontRevised.DataRef.AccessServiceAPISoap {
        
        public AccessServiceAPISoapClient() {
        }
        
        public AccessServiceAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessServiceAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.AddAnimalResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.AddAnimal(CodingPackFrontRevised.DataRef.AddAnimalRequest request) {
            return base.Channel.AddAnimal(request);
        }
        
        public bool AddAnimal(int intakenumber, string name, string breed, bool sex, int approxage, int age, bool sterilised, string description, string size) {
            CodingPackFrontRevised.DataRef.AddAnimalRequest inValue = new CodingPackFrontRevised.DataRef.AddAnimalRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.AddAnimalRequestBody();
            inValue.Body.intakenumber = intakenumber;
            inValue.Body.name = name;
            inValue.Body.breed = breed;
            inValue.Body.sex = sex;
            inValue.Body.approxage = approxage;
            inValue.Body.age = age;
            inValue.Body.sterilised = sterilised;
            inValue.Body.description = description;
            inValue.Body.size = size;
            CodingPackFrontRevised.DataRef.AddAnimalResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).AddAnimal(inValue);
            return retVal.Body.AddAnimalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddAnimalResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.AddAnimalAsync(CodingPackFrontRevised.DataRef.AddAnimalRequest request) {
            return base.Channel.AddAnimalAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddAnimalResponse> AddAnimalAsync(int intakenumber, string name, string breed, bool sex, int approxage, int age, bool sterilised, string description, string size) {
            CodingPackFrontRevised.DataRef.AddAnimalRequest inValue = new CodingPackFrontRevised.DataRef.AddAnimalRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.AddAnimalRequestBody();
            inValue.Body.intakenumber = intakenumber;
            inValue.Body.name = name;
            inValue.Body.breed = breed;
            inValue.Body.sex = sex;
            inValue.Body.approxage = approxage;
            inValue.Body.age = age;
            inValue.Body.sterilised = sterilised;
            inValue.Body.description = description;
            inValue.Body.size = size;
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).AddAnimalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.AddCampaignResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.AddCampaign(CodingPackFrontRevised.DataRef.AddCampaignRequest request) {
            return base.Channel.AddCampaign(request);
        }
        
        public bool AddCampaign(string name, string description, System.DateTime datefrom, System.DateTime dateto, bool online, bool fundraiser, string location, System.DateTime timeto, System.DateTime timefrom) {
            CodingPackFrontRevised.DataRef.AddCampaignRequest inValue = new CodingPackFrontRevised.DataRef.AddCampaignRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.AddCampaignRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.datefrom = datefrom;
            inValue.Body.dateto = dateto;
            inValue.Body.online = online;
            inValue.Body.fundraiser = fundraiser;
            inValue.Body.location = location;
            inValue.Body.timeto = timeto;
            inValue.Body.timefrom = timefrom;
            CodingPackFrontRevised.DataRef.AddCampaignResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).AddCampaign(inValue);
            return retVal.Body.AddCampaignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddCampaignResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.AddCampaignAsync(CodingPackFrontRevised.DataRef.AddCampaignRequest request) {
            return base.Channel.AddCampaignAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddCampaignResponse> AddCampaignAsync(string name, string description, System.DateTime datefrom, System.DateTime dateto, bool online, bool fundraiser, string location, System.DateTime timeto, System.DateTime timefrom) {
            CodingPackFrontRevised.DataRef.AddCampaignRequest inValue = new CodingPackFrontRevised.DataRef.AddCampaignRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.AddCampaignRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.datefrom = datefrom;
            inValue.Body.dateto = dateto;
            inValue.Body.online = online;
            inValue.Body.fundraiser = fundraiser;
            inValue.Body.location = location;
            inValue.Body.timeto = timeto;
            inValue.Body.timefrom = timefrom;
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).AddCampaignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.AddEmployeeResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.AddEmployee(CodingPackFrontRevised.DataRef.AddEmployeeRequest request) {
            return base.Channel.AddEmployee(request);
        }
        
        public bool AddEmployee(string name, string surname, string contactnumber, string email, bool volunteer) {
            CodingPackFrontRevised.DataRef.AddEmployeeRequest inValue = new CodingPackFrontRevised.DataRef.AddEmployeeRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.AddEmployeeRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.contactnumber = contactnumber;
            inValue.Body.email = email;
            inValue.Body.volunteer = volunteer;
            CodingPackFrontRevised.DataRef.AddEmployeeResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).AddEmployee(inValue);
            return retVal.Body.AddEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddEmployeeResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.AddEmployeeAsync(CodingPackFrontRevised.DataRef.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.AddEmployeeResponse> AddEmployeeAsync(string name, string surname, string contactnumber, string email, bool volunteer) {
            CodingPackFrontRevised.DataRef.AddEmployeeRequest inValue = new CodingPackFrontRevised.DataRef.AddEmployeeRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.AddEmployeeRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.contactnumber = contactnumber;
            inValue.Body.email = email;
            inValue.Body.volunteer = volunteer;
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).AddEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.getAllAnimalsResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.getAllAnimals(CodingPackFrontRevised.DataRef.getAllAnimalsRequest request) {
            return base.Channel.getAllAnimals(request);
        }
        
        public CodingPackFrontRevised.DataRef.Animal[] getAllAnimals() {
            CodingPackFrontRevised.DataRef.getAllAnimalsRequest inValue = new CodingPackFrontRevised.DataRef.getAllAnimalsRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.getAllAnimalsRequestBody();
            CodingPackFrontRevised.DataRef.getAllAnimalsResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).getAllAnimals(inValue);
            return retVal.Body.getAllAnimalsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllAnimalsResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.getAllAnimalsAsync(CodingPackFrontRevised.DataRef.getAllAnimalsRequest request) {
            return base.Channel.getAllAnimalsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllAnimalsResponse> getAllAnimalsAsync() {
            CodingPackFrontRevised.DataRef.getAllAnimalsRequest inValue = new CodingPackFrontRevised.DataRef.getAllAnimalsRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.getAllAnimalsRequestBody();
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).getAllAnimalsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.getAllCampaignsResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.getAllCampaigns(CodingPackFrontRevised.DataRef.getAllCampaignsRequest request) {
            return base.Channel.getAllCampaigns(request);
        }
        
        public CodingPackFrontRevised.DataRef.Campaign[] getAllCampaigns() {
            CodingPackFrontRevised.DataRef.getAllCampaignsRequest inValue = new CodingPackFrontRevised.DataRef.getAllCampaignsRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.getAllCampaignsRequestBody();
            CodingPackFrontRevised.DataRef.getAllCampaignsResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).getAllCampaigns(inValue);
            return retVal.Body.getAllCampaignsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllCampaignsResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.getAllCampaignsAsync(CodingPackFrontRevised.DataRef.getAllCampaignsRequest request) {
            return base.Channel.getAllCampaignsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllCampaignsResponse> getAllCampaignsAsync() {
            CodingPackFrontRevised.DataRef.getAllCampaignsRequest inValue = new CodingPackFrontRevised.DataRef.getAllCampaignsRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.getAllCampaignsRequestBody();
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).getAllCampaignsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.getAllEmployeesResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.getAllEmployees(CodingPackFrontRevised.DataRef.getAllEmployeesRequest request) {
            return base.Channel.getAllEmployees(request);
        }
        
        public CodingPackFrontRevised.DataRef.Employee[] getAllEmployees() {
            CodingPackFrontRevised.DataRef.getAllEmployeesRequest inValue = new CodingPackFrontRevised.DataRef.getAllEmployeesRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.getAllEmployeesRequestBody();
            CodingPackFrontRevised.DataRef.getAllEmployeesResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).getAllEmployees(inValue);
            return retVal.Body.getAllEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllEmployeesResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.getAllEmployeesAsync(CodingPackFrontRevised.DataRef.getAllEmployeesRequest request) {
            return base.Channel.getAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.getAllEmployeesResponse> getAllEmployeesAsync() {
            CodingPackFrontRevised.DataRef.getAllEmployeesRequest inValue = new CodingPackFrontRevised.DataRef.getAllEmployeesRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.getAllEmployeesRequestBody();
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).getAllEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodingPackFrontRevised.DataRef.HelloWorldResponse CodingPackFrontRevised.DataRef.AccessServiceAPISoap.HelloWorld(CodingPackFrontRevised.DataRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CodingPackFrontRevised.DataRef.HelloWorldRequest inValue = new CodingPackFrontRevised.DataRef.HelloWorldRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.HelloWorldRequestBody();
            CodingPackFrontRevised.DataRef.HelloWorldResponse retVal = ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.HelloWorldResponse> CodingPackFrontRevised.DataRef.AccessServiceAPISoap.HelloWorldAsync(CodingPackFrontRevised.DataRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodingPackFrontRevised.DataRef.HelloWorldResponse> HelloWorldAsync() {
            CodingPackFrontRevised.DataRef.HelloWorldRequest inValue = new CodingPackFrontRevised.DataRef.HelloWorldRequest();
            inValue.Body = new CodingPackFrontRevised.DataRef.HelloWorldRequestBody();
            return ((CodingPackFrontRevised.DataRef.AccessServiceAPISoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
